### ISSUE TITLE
peer to peer review 18-08-2020

### ISSUE THREAD

**Issue by mikethreels** [Prabhakarzx/Ruby-OOP-Project-Game#8]
Hi Guys, 

your project looks good, it's very visible you understand the material.
It does look more complicated than it has to be though, try to make it a bit simpler.
also when you're playing the game and you enter a move the columns don't align anymore try to fix this with the #center method.

Again great job guys.
Team 122-the-Manx

**Comment by Prabhakarzx** [comment]
### Thank You @mikethreels! :100: 
We're looking into it.
